In [1]:
import pandas as pd
data=pd.read_csv("clv_data.csv")
data.head(10)

,Unnamed: 0,id,age,gender,income,days_on_platform,city,purchases
0,0,0,NaN,Male,126895,14.0,San Francisco,0
1,1,1,NaN,Male,161474,14.0,Tokyo,0
2,2,2,24.0,Male,104723,34.0,London,1
3,3,3,29.0,Male,43791,28.0,London,2
4,4,4,18.0,Female,132181,26.0,London,2
5,5,5,23.0,Male,12315,14.0,New York City,0
6,6,6,NaN,Male,51679,30.0,Tokyo,0
7,7,7,NaN,Female,53341,43.0,San Francisco,1
8,8,8,46.0,Male,129157,23.0,New York City,0
9,9,9,49.0,Female,76842,19.0,Tokyo,2

In [2]:
data.tail()

,Unnamed: 0,id,age,gender,income,days_on_platform,city,purchases
4995,4995,4995,NaN,Female,212261,28.0,San Francisco,1
4996,4996,4996,NaN,Male,70228,12.0,San Francisco,0
4997,4997,4997,NaN,Male,64995,14.0,New York City,0
4998,4998,4998,NaN,Male,56144,4.0,New York City,2
4999,4999,4999,NaN,Female,110977,29.0,London,0

In [3]:
data.isnull()

,Unnamed: 0,id,age,gender,income,days_on_platform,city,purchases
0,False,False,True,False,False,False,False,False
1,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
4995,False,False,True,False,False,False,False,False
4996,False,False,True,False,False,False,False,False
4997,False,False,True,False,False,False,False,False
4998,False,False,True,False,False,False,False,False
4999,False,False,True,False,False,False,False,False

In [4]:
data.dropna()

,Unnamed: 0,id,age,gender,income,days_on_platform,city,purchases
2,2,2,24.0,Male,104723,34.0,London,1
3,3,3,29.0,Male,43791,28.0,London,2
4,4,4,18.0,Female,132181,26.0,London,2
5,5,5,23.0,Male,12315,14.0,New York City,0
8,8,8,46.0,Male,129157,23.0,New York City,0
...,...,...,...,...,...,...,...,...
4986,4986,4986,23.0,Male,75425,6.0,London,1
4989,4989,4989,47.0,Female,84987,30.0,Tokyo,0
4990,4990,4990,33.0,Male,3020,89.0,New York City,0
4991,4991,4991,36.0,Female,26173,34.0,Tokyo,0
4992,4992,4992,26.0,Male,88858,14.0,Miami,3

In [5]:
import numpy as n
data["age"].replace(' ' ,n.nan)

0        NaN
1        NaN
2       24.0
3       29.0
4       18.0
        ...
4995     NaN
4996     NaN
4997     NaN
4998     NaN
4999     NaN
Name: age, Length: 5000, dtype: float64

In [6]:
data["age"].fillna('25')

0         25
1         25
2       24.0
3       29.0
4       18.0
        ...
4995      25
4996      25
4997      25
4998      25
4999      25
Name: age, Length: 5000, dtype: object

In [11]:
data.isnull().sum()

Unnamed: 0             0
id                     0
age                 2446
gender                 0
income                 0
days_on_platform     141
city                   0
purchases              0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["city.com"]=le.fit_transform(data["city"])
print(data["city.com"])

0       3
1       4
2       0
3       0
4       0
       ..
4995    3
4996    3
4997    2
4998    2
4999    0
Name: city.com, Length: 5000, dtype: int32